# This is a basic workflow to help you get started with Actions

name: AIoT-Benchmarks

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - 'framework/workload/DockerImages/aiotbench/Dockerfile'
      - 'framework/workload/DockerImages/aiotbench/*.py'
      - '.github/workflows/*.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        - name: Build the AIoTBench image
          run: docker build -t shreshthtuli/yolo framework/workload/DockerImages/aiotbench/
        - name: Push the AIoTBench image
          run: docker push shreshthtuli/aiotbench
