name: AIoT-Benchmarks

on:
  push:
    branches: [ master ]
    paths:
      - 'framework/workload/DockerImages/aiotbench/Dockerfile'
      - 'framework/workload/DockerImages/aiotbench/*.py'
      - '.github/workflows/*.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        - name: Build the AIoTBench image
          run: docker build -t shreshthtuli/yolo framework/workload/DockerImages/aiotbench/
        - name: Push the AIoTBench image
          run: docker push shreshthtuli/aiotbench
