name: AIoT-Benchmarks

on:
  push:
    branches: [ master ]
    paths:
      - 'framework/workload/DockerImages/AIoTBench/Dockerfile'
      - 'framework/workload/DockerImages/AIoTBench/*.py'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
          with:
            image: tonistiigi/binfmt:latest
            platforms: all

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Available platforms
          run: echo ${{ steps.buildx.outputs.platforms }}
        - name: Login to DockerHub Registry
          run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        - name: Build the AIoTBench image
          run: docker buildx build -t shreshthtuli/aiotbench --platform linux/amd64,linux/arm64/v8 framework/workload/DockerImages/AIoTBench/
        - name: Push the AIoTBench image
          run: docker push shreshthtuli/aiotbench
